version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  node:
    build: .
    stdin_open: true
    tty: true
    command: yarn dev
    volumes:
      - ${PWD}:/myapp
      - .dockerdev:/docker
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:@postgres/database_development
      TEST_DATABASE_URL: postgres://postgres:@postgres/database_test
      HISTFILE: /docker/.bash_history
    depends_on:
      - postgres
volumes:
  postgres:
